### PR TITLE
Feature/multistart

### PR DESCRIPTION
**Pull request by thchang**
Added multistarts to all solvers in ``parmoo/optimizers/lbfgsb.py``

 - For global LBFGSB solver, default number of starts is n+1
 - For local TR_LBFGSB solver, default number of starts is 2
 - For both, number of starts can be adjusted using optional 'opt_restarts' hyperparam
 - First start is always from the current minimum value for the current acquisition function, as seen in ParMOO current evaluation database (TR center for TR_LBFGSB)
 - Second start is found by evaluating the gradient of the surrogate at the first starting point, and following it to the boundary (typically a corner) of the bounding box
 - Third start and up are randomly sampled from the bounding box (or TR bounds)

### CODE REVIEW

**Comment by thchang** [comment]
Note, it appears that GitHub Actions no longer supports Python 3.6

actions/setup-python#544

Therefore, I do not think we are able to support this version either, am moving to 3.8

**Review by wildsm — COMMENTED** [review]
Add restarts, corrects comments; updates py versions for github actions

**Comment by wildsm** [comment]
> Note, it appears that GitHub Actions no longer supports Python 3.6
> 
> [actions/setup-python#544](https://github.com/actions/setup-python/issues/544)
> 
> Therefore, I do not think we are able to support this version either, am moving to 3.8

hard to tell from this link whether this is here to stay (people jumping onto that link seem to be as much of a vote for may as well as move as anything else ?!)

**Review by wildsm — APPROVED** [review]

**Comment by thchang** [comment]
Agreed, it is unclear, but the message posted when closing the issue in November stated that as of now, they are dropping support for 3.6.  If they re-add support in the future, we can consider supporting older versions as well.

**Pull request merged**
