### PR TITLE
Update parmoo-ci.yml

### PR DESCRIPTION
**Pull request by wildsm**
WIP on coverage reports

### CODE REVIEW

**Comment by wildsm** [comment]
The first run succeeds and then subsequent ones reasonably complain about subsequent builds:

`Detected coverage file: .coverage
🚀 Posting coverage data to https://coveralls.io/api/v1/jobs
---
Error: Unprocessable Entity
Response: {"message":"Can't add a job to a build that is already closed. Build 10334843724 is closed. See docs.coveralls.io/parallel-builds","error":true}
---
🚨 Oops! It looks like your request was not processible by Coveralls.
This is often the is the result of an incorrectly set repo token.
More info/troubleshooting here: https://docs.coveralls.io/
- 💛, Coveralls`

Badge added but shows unknown coverage despite the 82.67% number on coveralls; it could be that this is associated with the main branch being the source of the badge coverage.

**Comment by wildsm** [comment]
Still did not update badge, but I've changed the coveralls settings based on the warning here.

**Comment by thchang** [comment]
So is the issue that it can't run again once it has finished generating the report?

Could we try running on only one entry in the build matrix?

Add something like this to the coveralls step?
```
 if: matrix.os == 'ubuntu-latest' && matrix['python-version'] == '3.11'
```

**Comment by thchang** [comment]
I think this might be working now, but it's hard to tell.  I think the coverage is unknown because the badge's target is set to `main`, and we haven't run this workflow on `main` yet to generate its coverage report

**Comment by wildsm** [comment]
Yep, Can you review me in so we can go to develop and test a step farther via draft PR to main?

**Review by thchang — APPROVED** [review]

**Comment by thchang** [comment]
Merged in -- leaving this branch open for now in case more changes are needed, but we should close it in the future

**Pull request merged**
