### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by wildsm**

### CODE REVIEW

**Comment by wildsm** [comment]
WIP - Do not yet approve/merge

**Comment by wildsm** [comment]
As shown at https://github.com/parmoo/parmoo/blob/feature/coveragebadge/README.rst
The badge is now correctly displaying now that develop and main are used at https://coveralls.io/github/parmoo/parmoo

**Comment by wildsm** [comment]
We need to add to the release process to check the coverage report being merged from the release and/or develop branch to ensure that the badge on main is tracking main. (and maybe that the badge on develop is reset to track develop post release)

**Comment by wildsm** [comment]
This PR is now ready for review

**Comment by wildsm** [comment]
> WIP - Do not yet approve/merge

Updated

**Comment by wildsm** [comment]
Opened #93

**Review by thchang — APPROVED** [review]

**Pull request merged**
